# Generated by Django 5.2.4 on 2025-07-08 09:25

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtb_v5_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
